#!/usr/bin/env python
from pikepdf import Pdf
import argparse
import shutil

def main():
  example_text = (
    'examples:\n\n'
    '%(prog)s input.pdf -o output.pdf\n'
    '%(prog)s input.pdf -o output.pdf --password 1234\n'
    '%(prog)s input.pdf -o output.pdf --stdin-password\n'
    'echo 1234 | %(prog)s input.pdf -o output.pdf --stdin-password\n'
    '%(prog)s input.pdf -b\n'
  )
  parser = argparse.ArgumentParser(
    description="A simple script that converts PDFs to versions without permission restrictions",
    epilog=example_text,
    formatter_class=argparse.RawDescriptionHelpFormatter
  )
  parser.add_argument("input", help="input PDF file")
  parser.add_argument("-p", "--password", help="password for the input PDF file", default="")
  parser.add_argument("--stdin-password", help="read password from stdin (this will override the --password or -p argument)", action="store_true")
  parser.add_argument("-o", "--output", help="output PDF file, default: output.pdf", default=None)
  parser.add_argument("-b", "--backup", help="the original file will be saved with the extension .bak, and the default output will be the original one", action="store_true")
  args = parser.parse_args()
  dst = Pdf.new()
  password = args.password
  output = "output.pdf"
  if args.backup:
    output = args.input
    new_input = f"{args.input}.bak"
    shutil.move(args.input, new_input)
    args.input = new_input
  if args.output:
    output = args.output
  if args.stdin_password:
    password = input("Warning, the password is visible if it is typed\nPassword: ")
  with Pdf.open(args.input, password=password) as pdf:
    for page in pdf.pages:
      dst.pages.append(page)
    dst.save(output)

if __name__ == "__main__":
  main()
